<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Cubeglass.Voxel.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="FsCheck" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voxel\Cubeglass.Voxel.csproj" />
  </ItemGroup>

</Project>
