"""Contract-compatibility gate for the frozen Cubeglass ABI surface.

The gate freezes the C ABI (``contracts/cg_types.h``,
``contracts/cg_unity_bridge.h``), the shared C++ contract vocabulary
(``contracts/cpp/ports.hpp``, ``contracts/cpp/result.hpp``) and the golden
transform fixture (``contracts/golden/transforms.json``) in
``contracts/abi-baseline.json``. The fingerprint is computed over the contract
text with comments and whitespace stripped, so formatting-only edits pass while
any real change to a struct, enum, function declaration, macro or fixture case
changes it.

Truth is anchored in *code*, not in the generated baseline. Two constants in
this module are the independent record a baseline-only edit cannot forge:

- :data:`KNOWN_ABI_VERSIONS` pins the source version each artefact must declare
  (``CG_ABI_VERSION`` in ``contracts/cg_types.h``; the ``schema`` field of
  ``contracts/golden/transforms.json``);
- :data:`KNOWN_FINGERPRINTS` pins the normalised-declaration SHA-256 of every
  contract file.

``check_contracts`` recomputes the live fingerprints and fails when any of them
differs from :data:`KNOWN_FINGERPRINTS`, before it even looks at the baseline.
Intended drift therefore requires a review-visible edit of the code constant
(plus a regenerated baseline); no baseline-only edit can admit it. The
version-bump discipline is additionally checked by the source-vs-
:data:`KNOWN_ABI_VERSIONS` anchor, but because both constants live in this file,
an edit of ``KNOWN_FINGERPRINTS`` that leaves the version and the anchor at
their old values would pass the gate: the bump tied to a fingerprint change
remains a review-enforced convention, not a machine-enforced one.

``--update`` refuses while the live fingerprint differs from the code constant,
printing exactly which constant to edit; it may otherwise refresh the baseline
at any time (that is how a stale or tampered baseline is repaired).

Only the standard library is used and the fingerprint is deterministic:

- a backslash-newline continuation is spliced first (the C translation phase
  before comment removal), preserving line numbers;
- ``//`` and ``/* ... */`` comments are removed with a string/char-literal
  aware scanner for C++ and C# (including C# verbatim, interpolated and raw
  strings), so ``"/*"`` in a string cannot swallow a region;
- every contract file is read as UTF-8 and normalised by removing comments and
  all whitespace;
- each file's SHA-256 is recorded, and the baseline fingerprint is the SHA-256
  over the sorted ``relative-path:file-hash`` lines.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import cast

CONTRACT_FILES: tuple[tuple[str, ...], ...] = (
    ("contracts", "cg_types.h"),
    ("contracts", "cg_unity_bridge.h"),
    ("contracts", "cpp", "ports.hpp"),
    ("contracts", "cpp", "result.hpp"),
    ("contracts", "golden", "transforms.json"),
)
BASELINE_PARTS: tuple[str, ...] = ("contracts", "abi-baseline.json")
VERSION_MACRO = "CG_ABI_VERSION"

# Files under contracts/ that are deliberately *not* part of the frozen ABI
# surface. Every one carries a reason, and the contract-coverage check fails on
# an uncovered file as well as on a stale exemption, so a new contract artefact
# cannot slip past the gate silently (TD-039).
EXEMPT_CONTRACT_FILES: dict[str, str] = {
    "contracts/abi-baseline.json": (
        "generated bookkeeping regenerated by `depcheck contracts --update`; "
        "the code constants are the trust anchor, not this file"
    ),
    "contracts/layers.json": (
        "dependency-rule configuration, not ABI surface; enforced by the depcheck "
        "rule and layers-completeness checks, and changed without an ABI bump"
    ),
    "contracts/licence-allowlist.json": (
        "licence policy data, not ABI surface; enforced by the licence gate"
    ),
    "contracts/.gitkeep": "empty placeholder that keeps the contracts/ directory in git",
}

# Known-good source versions, maintained in code on purpose: the anchor is the
# independent record that a baseline-only edit cannot forge. Keys are
# repository-relative paths; C/C++ headers are read for ``VERSION_MACRO`` and
# JSON fixtures for their integer ``schema``.
KNOWN_ABI_VERSIONS: dict[str, int] = {
    "contracts/cg_types.h": 2,
    "contracts/golden/transforms.json": 1,
}

# Known-good normalised-declaration SHA-256 per contract file, maintained in
# code on purpose. Any live file whose hash differs fails the gate regardless of
# what the baseline says; update the constant (and bump the ABI version) as a
# reviewed change, then regenerate the baseline with
# ``python -m depcheck contracts --update``.
KNOWN_FINGERPRINTS: dict[str, str] = {
    "contracts/cg_types.h": "e0d76b949966224211693b414a8d8be916461ca0493a941aa1a297037d0fbaf6",
    "contracts/cg_unity_bridge.h": "467727ee3306be1467d9b3408d7fffcbbca0f3036c2d0133a0e04cfb11ef089e",
    "contracts/cpp/ports.hpp": "13149756e58b664c3e610fc18923f40aae49402dc664cb218e0638d670c4af05",
    "contracts/cpp/result.hpp": "2dce1d4b7ee35a7f4df6a2bc518320975a5ccd7390f0b0c1529fa4394e89dd64",
    "contracts/golden/transforms.json": "db36e68d8ac08af5cc8b18d70bb1c171229b6438e932fc68b7f47b43808854f0",
}

_WHITESPACE_RE = re.compile(r"\s+")
# Anchored to the start of a line and applied to comment-stripped text, so a
# commented-out `#define CG_ABI_VERSION 99` can never masquerade as a bump.
_VERSION_RE = re.compile(rf"(?m)^[ \t]*#[ \t]*define[ \t]+{VERSION_MACRO}[ \t]+(\d+)")

_CPP_RAW_PREFIXES: tuple[str, ...] = ("u8R", "uR", "UR", "LR", "R")

# C# interpolation nesting supported by the literal scanner: holes are scanned
# recursively so a qualified name inside `$"{...}"` is still code. Past this
# depth the hole is masked whole (fail-safe, documented as a remaining textual
# limit in docs/ci.md).
_MAX_INTERPOLATION_DEPTH = 8


class ContractError(Exception):
    """Raised when a contract file or the ABI baseline cannot be used.

    A missing contract file, a missing ``CG_ABI_VERSION`` declare or a malformed
    baseline would otherwise let the gate pass or fail for the wrong reason, so
    each is surfaced as an explicit error.
    """


@dataclass(frozen=True)
class ContractState:
    """The ABI version and normalised fingerprint of the contract surface."""

    version: int
    fingerprint: str
    files: dict[str, str]


def _relative(parts: tuple[str, ...]) -> str:
    return "/".join(parts)


def _splice_lines(text: str) -> str:
    """Splice backslash-newline continuations, preserving the line count.

    This is the C translation phase that precedes comment removal, so a
    directive split as ``#in\\`` + newline + ``clude <x>`` is one logical line
    before any other parsing. Every consumed physical line is left as a blank
    line so line numbers in later diagnostics do not shift.
    """

    lines = text.split("\n")
    spliced_lines: list[str] = []
    index = 0
    while index < len(lines):
        current = lines[index]
        spliced = 0
        while True:
            current = current.removesuffix("\r")
            if current.endswith("\\") and index + 1 < len(lines):
                current = current[:-1] + lines[index + 1]
                index += 1
                spliced += 1
            else:
                break
        spliced_lines.append(current)
        spliced_lines.extend([""] * spliced)
        index += 1
    return "\n".join(spliced_lines)


def _quoted_end(text: str, start: int, quote: str, *, verbatim: bool) -> int:
    """Return the index just past a quoted literal starting at ``start``.

    ``verbatim`` covers C# verbatim strings (``@"..."``) where ``""`` is an
    escaped quote and backslashes are literal. Non-verbatim literals stop at an
    unescaped newline, so an unterminated quote cannot swallow the rest of the
    file.
    """

    index = start + 1
    length = len(text)
    while index < length:
        character = text[index]
        if verbatim:
            if character == quote:
                if index + 1 < length and text[index + 1] == quote:
                    index += 2
                    continue
                return index + 1
            index += 1
        else:
            if character == "\\":
                index += 2
                continue
            if character == quote:
                return index + 1
            if character == "\n":
                return index
            index += 1
    return length


def _raw_end(text: str, quote_index: int, quote_count: int) -> int:
    """Return the index just past a C# raw string (``\"\"\"...\"\"\"``)."""

    closing = '"' * quote_count
    close = text.find(closing, quote_index + quote_count)
    return len(text) if close == -1 else close + quote_count


def _csharp_literal(text: str, index: int) -> tuple[int, int, bool, int] | None:
    """Return ``(quote_index, quote_count, verbatim, dollars)`` for a C# literal prefix."""

    cursor = index
    while cursor < len(text) and text[cursor] in "$@":
        cursor += 1
    quote_count = 0
    while cursor + quote_count < len(text) and text[cursor + quote_count] == '"':
        quote_count += 1
    prefix = text[index:cursor]
    if quote_count >= 3 and "@" not in prefix:
        return cursor, quote_count, True, prefix.count("$")
    if quote_count == 1 and prefix in ("@", "$", "@$", "$@"):
        return cursor, 1, "@" in prefix, prefix.count("$")
    return None


def _masked_segment(segment: str) -> str:
    """Blank a segment, keeping its newlines so line numbers do not shift."""

    return "".join("\n" if character == "\n" else " " for character in segment)


def _split_hole_format(inner: str) -> str:
    """Return the expression part of an interpolation hole before a format ``:``.

    C# splits an interpolation ``{expr:format}`` at the first top-level colon;
    the format component is not code, so it must stay masked. A colon nested in
    brackets or quotes is part of the expression. The remaining textual limit is
    the ``::`` alias qualifier, which is treated as a format split (masks the
    rest of that hole) rather than mis-reported as code.
    """

    depth = 0
    cursor = 0
    while cursor < len(inner):
        character = inner[cursor]
        if character in "([{":
            depth += 1
            cursor += 1
            continue
        if character in ")]}":
            depth = max(0, depth - 1)
            cursor += 1
            continue
        if character == '"' or character in "$@":
            literal = _csharp_literal(inner, cursor)
            if literal is not None:
                quote_index, quote_count, verbatim, dollars = literal
                if dollars:
                    sink: list[str] = []
                    cursor = _copy_csharp_interpolated(
                        inner, cursor, quote_index, quote_count, dollars, sink, mask=True, depth=_MAX_INTERPOLATION_DEPTH
                    )
                elif quote_count >= 3:
                    cursor = _raw_end(inner, quote_index, quote_count)
                else:
                    cursor = _quoted_end(inner, quote_index, '"', verbatim=verbatim)
                continue
            if character == '"':
                cursor = _quoted_end(inner, cursor, '"', verbatim=False)
                continue
        if character == "'":
            cursor = _quoted_end(inner, cursor, "'", verbatim=False)
            continue
        if character == ":" and depth == 0:
            return inner[:cursor]
        cursor += 1
    return inner


def _interpolation_hole(text: str, start: int, open_token: str, close_token: str) -> tuple[int, str]:
    """Return ``(end, inner)`` for the hole beginning at ``start``.

    ``end`` is the index just past the matching close token; nested braces and
    string/char literals are skipped so a ``}`` inside a nested literal or hole
    cannot close the outer hole early. An unterminated hole consumes the rest of
    the text.
    """

    cursor = start + len(open_token)
    depth = 1
    while cursor < len(text):
        character = text[cursor]
        if character == '"' or character in "$@":
            literal = _csharp_literal(text, cursor)
            if literal is not None:
                quote_index, quote_count, verbatim, dollars = literal
                if dollars:
                    sink: list[str] = []
                    cursor = _copy_csharp_interpolated(
                        text, cursor, quote_index, quote_count, dollars, sink, mask=True, depth=_MAX_INTERPOLATION_DEPTH
                    )
                elif quote_count >= 3:
                    cursor = _raw_end(text, quote_index, quote_count)
                else:
                    cursor = _quoted_end(text, quote_index, '"', verbatim=verbatim)
                continue
            if character == '"':
                cursor = _quoted_end(text, cursor, '"', verbatim=False)
                continue
        if character == "'":
            cursor = _quoted_end(text, cursor, "'", verbatim=False)
            continue
        if text.startswith(open_token, cursor):
            depth += 1
            cursor += len(open_token)
            continue
        if text.startswith(close_token, cursor):
            depth -= 1
            if depth == 0:
                return cursor + len(close_token), text[start + len(open_token) : cursor]
            cursor += len(close_token)
            continue
        cursor += 1
    return len(text), text[start + len(open_token) :]


def _copy_csharp_interpolated(
    text: str,
    start: int,
    quote_index: int,
    quote_count: int,
    dollars: int,
    out: list[str],
    *,
    mask: bool,
    depth: int,
) -> int:
    """Copy or mask a C# interpolated string, keeping interpolation holes as code.

    Literal segments are copied or blanked according to ``mask``; each hole's
    expression is recursively scanned (so ``$"{System.IO.File.ReadAllText(p)}"``
    still exposes ``System.IO.File`` to the rule checks, TD-048) while its format
    component stays masked. Nested interpolated strings inside a hole are handled
    recursively to :data:`_MAX_INTERPOLATION_DEPTH`; a deeper hole is masked
    whole.
    """

    prefix = text[start : quote_index + quote_count]
    out.append(_masked_segment(prefix) if mask else prefix)
    if quote_count >= 3:
        open_token = "{" * max(dollars, 1)
        close_token = "}" * max(dollars, 1)
        cursor = quote_index + quote_count
        terminator = '"' * quote_count
    else:
        open_token = "{"
        close_token = "}"
        cursor = quote_index + 1
        terminator = ""
    length = len(text)
    while cursor < length:
        if terminator:
            if text.startswith(terminator, cursor):
                out.append(_masked_segment(terminator) if mask else terminator)
                return cursor + len(terminator)
        else:
            character = text[cursor]
            if character == "\\" and quote_count < 3 and "@" not in prefix:
                segment = text[cursor : cursor + 2]
                out.append(_masked_segment(segment) if mask else segment)
                cursor += len(segment)
                continue
            if character == "\n" and "@" not in prefix:
                return cursor
            if character == '"':
                if "@" in prefix and cursor + 1 < length and text[cursor + 1] == '"':
                    out.append("  " if mask else '""')
                    cursor += 2
                    continue
                out.append(" " if mask else '"')
                return cursor + 1
        if text.startswith(open_token, cursor):
            if quote_count < 3 and open_token == "{" and text.startswith("{{", cursor):
                # In a non-raw interpolated string `{{` is an escaped literal
                # brace, not the start of a hole.
                out.append("  " if mask else "{{")
                cursor += 2
                continue
            end, inner = _interpolation_hole(text, cursor, open_token, close_token)
            expression = _split_hole_format(inner)
            format_part = inner[len(expression) :]
            out.append(" " * len(open_token) if mask else open_token)
            if depth < _MAX_INTERPOLATION_DEPTH:
                out.append(_scan(expression, mask_literals=mask, _depth=depth + 1))
            else:
                out.append(_masked_segment(expression) if mask else expression)
            out.append(_masked_segment(format_part))
            out.append(" " * len(close_token) if mask else close_token)
            cursor = end
            continue
        if text.startswith(close_token, cursor) and close_token != open_token:
            out.append(" " * len(close_token) if mask else close_token)
            cursor += len(close_token)
            continue
        character = text[cursor]
        out.append(_masked_segment(character) if mask else character)
        cursor += 1
    return length


def _scan(text: str, *, mask_literals: bool, _depth: int = 0) -> str:
    """Remove comments outside string/char literals, optionally masking them."""

    out: list[str] = []
    index = 0
    length = len(text)
    while index < length:
        character = text[index]
        if character == "/" and index + 1 < length:
            following = text[index + 1]
            if following == "/":
                newline = text.find("\n", index)
                if newline == -1:
                    break
                index = newline
                continue
            if following == "*":
                closing = text.find("*/", index + 2)
                if closing == -1:
                    out.append("\n" * text.count("\n", index))
                    break
                commented = text[index : closing + 2]
                out.append("\n" * commented.count("\n"))
                index = closing + 2
                continue
        if character in "$@":
            literal = _csharp_literal(text, index)
            if literal is not None:
                quote_index, quote_count, verbatim, dollars = literal
                if dollars:
                    index = _copy_csharp_interpolated(
                        text,
                        index,
                        quote_index,
                        quote_count,
                        dollars,
                        out,
                        mask=mask_literals,
                        depth=_depth,
                    )
                    continue
                end = (
                    _raw_end(text, quote_index, quote_count)
                    if quote_count >= 3
                    else _quoted_end(text, quote_index, '"', verbatim=verbatim)
                )
                _copy_literal(text, index, end, out, mask=mask_literals)
                index = end
                continue
        if character == '"':
            quote_count = 0
            while index + quote_count < length and text[index + quote_count] == '"':
                quote_count += 1
            if quote_count >= 3:
                end = _raw_end(text, index, quote_count)
            else:
                end = _quoted_end(text, index, '"', verbatim=False)
            _copy_literal(text, index, end, out, mask=mask_literals)
            index = end
            continue
        if character == "'" and not (index > 0 and (text[index - 1].isalnum() or text[index - 1] == "_")):
            end = _quoted_end(text, index, "'", verbatim=False)
            _copy_literal(text, index, end, out, mask=mask_literals)
            index = end
            continue
        raw_end = _cpp_raw_end(text, index)
        if raw_end is not None:
            _copy_literal(text, index, raw_end, out, mask=mask_literals)
            index = raw_end
            continue
        # C++ phase-1 digraphs, translated in code only: a literal that spells
        # `%:include` stays literal text and must not become a directive.
        if character == "%" and text.startswith("%:%:", index):
            out.append("##")
            index += 4
            continue
        if character == "%" and text.startswith("%:", index):
            out.append("#")
            index += 2
            continue
        out.append(character)
        index += 1
    return "".join(out)


def _cpp_raw_end(text: str, index: int) -> int | None:
    """Return the end of a C++ raw string literal starting at ``index``."""

    if index > 0 and (text[index - 1].isalnum() or text[index - 1] == "_"):
        return None
    for prefix in _CPP_RAW_PREFIXES:
        if not text.startswith(prefix + '"', index):
            continue
        quote_index = index + len(prefix)
        paren = text.find("(", quote_index + 1, quote_index + 18)
        if paren == -1:
            return None
        delimiter = text[quote_index + 1 : paren]
        if any(character in delimiter for character in ('"', "\\", " ", "\t", "\n", "\r")):
            return None
        closing = ")" + delimiter + '"'
        close = text.find(closing, paren + 1)
        return len(text) if close == -1 else close + len(closing)
    return None


def _copy_literal(text: str, start: int, end: int, out: list[str], *, mask: bool) -> None:
    """Copy or blank a literal span, keeping its newlines for line numbers."""

    segment = text[start:end]
    if mask:
        out.append("".join("\n" if character == "\n" else " " for character in segment))
    else:
        out.append(segment)


def strip_comments(text: str) -> str:
    """Remove comments outside literals, keeping line breaks and line numbers."""

    return _scan(_splice_lines(text), mask_literals=False)


def mask_string_literals(text: str) -> str:
    """Remove comments and blank out literal contents, keeping line numbers.

    Used for token scans (for example C# fully-qualified namespace matching)
    where text inside a string must never count as code.
    """

    return _scan(_splice_lines(text), mask_literals=True)


def normalise(text: str) -> str:
    """Strip comments and whitespace so formatting-only edits are invisible."""

    return _WHITESPACE_RE.sub("", strip_comments(text))


def _read_contracts(root: Path) -> dict[str, str]:
    texts: dict[str, str] = {}
    for parts in CONTRACT_FILES:
        relative = _relative(parts)
        path = root.joinpath(*parts)
        if not path.is_file():
            raise ContractError(f"missing contract file: {relative}")
        texts[relative] = path.read_text(encoding="utf-8")
    return texts


def contract_coverage(root: Path) -> list[str]:
    """Return every ``contracts/`` file that is neither fingerprinted nor exempt.

    The ABI gate only vouches for the files in :data:`CONTRACT_FILES`; a new
    artefact under ``contracts/`` would otherwise sit outside every gate. This
    check makes the coverage explicit: each file must be fingerprinted or carry an
    exemption with a reason, and a file cannot be both (TD-039). An exemption whose
    file has gone is tolerated: it is inert and the alternative would fail the
    fixture trees that model only part of ``contracts/``.
    """

    base = root / "contracts"
    if not base.is_dir():
        return []
    covered = {_relative(parts) for parts in CONTRACT_FILES}
    actual = {path.relative_to(root).as_posix() for path in base.rglob("*") if path.is_file()}
    failures: list[str] = []
    for relative in sorted(actual):
        if relative in covered:
            if relative in EXEMPT_CONTRACT_FILES:
                failures.append(
                    f"contracts: {relative} is both fingerprinted and exempt; keep exactly one "
                    f"so the gate's coverage is unambiguous"
                )
            continue
        if relative not in EXEMPT_CONTRACT_FILES:
            failures.append(
                f"contracts: {relative} is neither fingerprinted by CONTRACT_FILES nor exempted; "
                f"add it to CONTRACT_FILES (and regenerate contracts/abi-baseline.json) or to "
                f"EXEMPT_CONTRACT_FILES with a reason"
            )
    return failures


def extract_abi_version(texts: dict[str, str]) -> int:
    """Return ``CG_ABI_VERSION`` from the contract headers.

    The macro lives in ``contracts/cg_types.h``; scanning every contract file
    keeps the check working if the declaration ever moves. Comment-stripped text
    is scanned so a commented-out define cannot fake a version bump.
    """

    for relative in sorted(texts):
        match = _VERSION_RE.search(strip_comments(texts[relative]))
        if match is not None:
            return int(match.group(1))
    raise ContractError(f"no {VERSION_MACRO} define found in the contract headers")


def _fingerprint(files: dict[str, str]) -> str:
    """SHA-256 over the sorted ``relative-path:file-hash`` lines."""

    return hashlib.sha256(
        "\n".join(f"{relative}:{files[relative]}" for relative in sorted(files)).encode("utf-8")
    ).hexdigest()


def compute_state(root: Path) -> ContractState:
    """Compute the normalised ABI version and fingerprint under ``root``."""

    texts = _read_contracts(root)
    files = {relative: hashlib.sha256(normalise(text).encode("utf-8")).hexdigest() for relative, text in texts.items()}
    return ContractState(version=extract_abi_version(texts), fingerprint=_fingerprint(files), files=files)


def _read_anchor_version(texts: dict[str, str], relative: str) -> int:
    """Extract the version the anchor tracks for ``relative``.

    C/C++ contract files are read for ``VERSION_MACRO``; JSON files (the golden
    fixture) for their integer ``schema``.
    """

    text = texts.get(relative)
    if text is None:
        raise ContractError(f"missing contract file: {relative}")
    if relative.endswith(".json"):
        try:
            data: object = json.loads(text)
        except json.JSONDecodeError as error:
            raise ContractError(f"{relative}: invalid JSON ({error})") from error
        if not isinstance(data, dict):
            raise ContractError(f"{relative}: expected a JSON object at the top level")
        schema = cast(dict[object, object], data).get("schema")
        if not isinstance(schema, int) or isinstance(schema, bool):
            raise ContractError(f"{relative}: expected an integer 'schema'")
        return schema
    match = _VERSION_RE.search(strip_comments(text))
    if match is None:
        raise ContractError(f"{relative}: no {VERSION_MACRO} define found")
    return int(match.group(1))


def _check_anchors(texts: dict[str, str]) -> list[str]:
    """Return the failures where a source version disagrees with the code anchor."""

    update = "`python -m depcheck contracts --update`"
    failures: list[str] = []
    for relative, expected in KNOWN_ABI_VERSIONS.items():
        actual = _read_anchor_version(texts, relative)
        if actual != expected:
            failures.append(
                f"contracts: {relative} declares version {actual}, but the code anchor "
                f"KNOWN_ABI_VERSIONS records {expected}; a real contract change needs the source "
                f"version bump, both code anchors updated and then {update}"
            )
    return failures


def _fingerprint_failures(state: ContractState) -> list[str]:
    """Return the live files whose hash disagrees with the code anchor."""

    failures: list[str] = []
    for relative in sorted(set(KNOWN_FINGERPRINTS) | set(state.files)):
        actual = state.files.get(relative)
        expected = KNOWN_FINGERPRINTS.get(relative)
        if actual == expected:
            continue
        failures.append(
            f"contracts: {relative} hashes to {actual} but the code anchor KNOWN_FINGERPRINTS records "
            f"{expected}; if the change is intended, bump the source ABI version, update KNOWN_ABI_VERSIONS "
            f"and KNOWN_FINGERPRINTS in python/depcheck/contracts.py, then run "
            f"`python -m depcheck contracts --update`"
        )
    return failures


def _parse_baseline(text: str, label: str) -> ContractState:
    """Parse a baseline document, raising :class:`ContractError` on bad shape."""

    try:
        data: object = json.loads(text)
    except json.JSONDecodeError as error:
        raise ContractError(f"{label}: invalid JSON ({error})") from error
    if not isinstance(data, dict):
        raise ContractError(f"{label}: expected a JSON object at the top level")
    baseline = cast(dict[object, object], data)
    version = baseline.get("abiVersion")
    fingerprint = baseline.get("fingerprint")
    files = baseline.get("files")
    if not isinstance(version, int) or not isinstance(fingerprint, str) or not isinstance(files, dict):
        raise ContractError(
            f"{label}: expected 'abiVersion' (int), 'fingerprint' (str) and 'files' (object)"
        )
    return ContractState(
        version=version,
        fingerprint=fingerprint,
        files={str(key): str(value) for key, value in cast(dict[object, object], files).items()},
    )


def load_baseline(root: Path) -> ContractState | None:
    """Load ``contracts/abi-baseline.json``; ``None`` when it does not exist."""

    path = root.joinpath(*BASELINE_PARTS)
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise ContractError(f"{_relative(BASELINE_PARTS)}: cannot read baseline ({error})") from error
    return _parse_baseline(text, _relative(BASELINE_PARTS))


def _git(root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    """Run a read-only git command in ``root``."""

    try:
        return subprocess.run(
            ["git", "-C", str(root), *arguments],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as error:
        raise ContractError(
            "git is not available; the merge-base version-bump check needs a git checkout"
        ) from error


def load_baseline_from_git(root: Path, ref: str) -> ContractState | None:
    """Load the baseline as it existed at the merge-base with ``ref``.

    The revision is ``git merge-base <ref> HEAD`` when a merge base exists, with
    ``ref`` itself as the fallback (for a direct child or a detached ref). A
    missing baseline at that revision returns ``None`` (nothing to compare, the
    bootstrap case). An unresolvable ref is a hard error so a mistyped CI base ref
    cannot silently disable the check (TD-049).
    """

    resolvable = _git(root, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}")
    if resolvable.returncode != 0:
        raise ContractError(f"cannot resolve the --since base ref {ref!r} in {root}")
    merge_base = _git(root, "merge-base", ref, "HEAD")
    revision = merge_base.stdout.strip() if merge_base.returncode == 0 else ref
    if not revision:
        revision = ref
    shown = _git(root, "show", f"{revision}:{_relative(BASELINE_PARTS)}")
    if shown.returncode != 0:
        return None
    return _parse_baseline(shown.stdout, f"{ref}:{_relative(BASELINE_PARTS)}")


def _version_bump_failures(root: Path, state: ContractState, base_ref: str) -> list[str]:
    """Flag a contract change whose ABI version was not bumped against ``base_ref``."""

    base = load_baseline_from_git(root, base_ref)
    if base is None:
        return []
    if base.version != state.version:
        return []
    changed = changed_files(state, base)
    if not changed:
        return []
    detail = ", ".join(changed)
    return [
        (
            f"contracts: the contract surface changed ({detail}) relative to {base_ref}, but "
            f"{VERSION_MACRO} stayed at {state.version}; bump {VERSION_MACRO} in contracts/cg_types.h, "
            f"update KNOWN_ABI_VERSIONS/KNOWN_FINGERPRINTS, then run "
            f"`python -m depcheck contracts --update`"
        )
    ]


def _write_baseline(root: Path, state: ContractState) -> None:
    path = root.joinpath(*BASELINE_PARTS)
    payload = {"abiVersion": state.version, "fingerprint": state.fingerprint, "files": state.files}
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def changed_files(state: ContractState, baseline: ContractState) -> list[str]:
    """Return the contract files whose normalised content differs."""

    return sorted(
        relative for relative in state.files if baseline.files.get(relative) != state.files.get(relative)
    )


def check_contracts(root: Path, *, base_ref: str | None = None) -> list[str]:
    """Return the contract-compatibility failures under ``root``.

    The live normalised fingerprints are compared against the hardcoded
    :data:`KNOWN_FINGERPRINTS` first, so a source edit fails even when the
    baseline was consistently rewritten to match it. Source versions must agree
    with :data:`KNOWN_ABI_VERSIONS`, and the baseline (bookkeeping only) must
    record the version and hashes of the live surface; any baseline-only edit
    therefore fails without ever being able to admit drift. Every file under
    ``contracts/`` must be fingerprinted or exempted (TD-039), and when
    ``base_ref`` is given (the CI merge-base), a surface change that leaves
    ``CG_ABI_VERSION`` unchanged fails the bump discipline (TD-049).
    """

    resolved = root.resolve()
    coverage_failures = contract_coverage(resolved)
    if coverage_failures:
        return coverage_failures
    texts = _read_contracts(resolved)
    state = compute_state(resolved)
    fingerprint_failures = _fingerprint_failures(state)
    if fingerprint_failures:
        return fingerprint_failures
    anchor_failures = _check_anchors(texts)
    if anchor_failures:
        return anchor_failures
    baseline = load_baseline(resolved)
    if baseline is None:
        return [f"{_relative(BASELINE_PARTS)}: missing ABI baseline; run `python -m depcheck contracts --update`"]
    if baseline.version != state.version:
        return [
            (
                f"{_relative(BASELINE_PARTS)}: abiVersion {baseline.version} disagrees with "
                f"{VERSION_MACRO} {state.version}; the baseline does not record the live surface "
                f"(bookkeeping only); run `python -m depcheck contracts --update`"
            )
        ]
    if baseline.files != state.files or baseline.fingerprint != state.fingerprint:
        detail = ", ".join(changed_files(state, baseline))
        return [
            (
                f"{_relative(BASELINE_PARTS)}: the recorded contract surface does not match the live "
                f"contract surface ({detail}); the baseline is bookkeeping and cannot vouch for the source; "
                f"run `python -m depcheck contracts --update`"
            )
        ]
    if base_ref:
        return _version_bump_failures(resolved, state, base_ref)
    return []


def update_baseline(root: Path) -> ContractState:
    """Regenerate the baseline once the live surface matches the code anchors.

    Returns the state that is now recorded. Raises :class:`ContractError` while
    a live fingerprint differs from :data:`KNOWN_FINGERPRINTS` or a source
    version differs from :data:`KNOWN_ABI_VERSIONS`, printing exactly which
    code constant to edit first, so ``--update`` cannot be used to accept a
    contract edit without updating the anchors in code. An uncovered file under
    ``contracts/`` is refused for the same reason (TD-039).
    """

    resolved = root.resolve()
    coverage_failures = contract_coverage(resolved)
    if coverage_failures:
        raise ContractError(f"refusing to update {_relative(BASELINE_PARTS)}: {coverage_failures[0]}")
    texts = _read_contracts(resolved)
    state = compute_state(resolved)
    fingerprint_failures = _fingerprint_failures(state)
    if fingerprint_failures:
        raise ContractError(f"refusing to update {_relative(BASELINE_PARTS)}: {fingerprint_failures[0]}")
    anchor_failures = _check_anchors(texts)
    if anchor_failures:
        raise ContractError(f"refusing to update {_relative(BASELINE_PARTS)}: {anchor_failures[0]}")
    _write_baseline(resolved, state)
    return state
