<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <RootNamespace>Cubeglass.Voxel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\blocks.json" />
    <PackageReference Include="System.Text.Json" />
    <InternalsVisibleTo Include="Cubeglass.Voxel.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreMath\Cubeglass.CoreMath.csproj" />
  </ItemGroup>

</Project>
